.TH JEFF_DWM 1 jeff_dwm\-VERSION
.SH NAME
jeff_dwm \- jeff's dynamic window manager
.SH SYNOPSIS
.B jeff_dwm
.RB [-Fv?V] [--first-run] [--simple-version] [--help] [--usage] [--version] 
.SH DESCRIPTION
dwm is a dynamic window manager for X. jeff_dwm is a custom build of dwm made
by JeffofBread. To learn more about jeff_dwm go to https://github.com/JeffofBread/jeff_dwm/.
To learn more about the original window manager jeff_dwm is based off, go to
https://dwm.suckless.org/.
.P
There are 14 different methods for controlling the layout of windows by default in jeff_dwm,
tile being the default. It is denoted by the []= symbol on the left side of the bar. These
various layouts control how windows are moved and sized as more windows are added or
removed from the desktop. Each desktop and tag can have its own layout controlling only
windows on that specific desktop and tag.
.P
Windows are grouped by tags. Each window can be tagged with one or multiple
tags. Selecting certain tags displays all windows with these tags. Only currently
active tags will be displayed on the bar. To enter a tag not shown on the bar,
refer to the keybinds.
.P
Each screen contains a small status bar which displays all active tags, the
layout, the title and logo of the focused window, as well as the system tray and 
dwmblocks text if the screen is focused. A floating window is indicated with an
empty square next to its name and a border. The selected tags are indicated by an 
underline under the tag icon.
.SH OPTIONS
.TP
.B \-F --first-run
Tells jeff_dwm to execute itself along with all programs defined in the array
startonce in autostart.h
.TP
.B \-s --simple-execute
Basic execute, avoids starting any programs in autostart.h, only for debugging
.TP
.B \-v --simple-version
Gives a simplified version output
.TP
.B \-V --version
Gives a more complex version output
.TP
.B \-? --help
Prints a simple help message, very similar to this options section
.TP
.B \--usage
Gives a small message to provide context on how to use jeff_dwm cli arguments
.SH Bindings
There are simply too many keybinds and mousebinds to list them all here, but I will provide the
most vital ones. To find the rest, check binds.h in your jeff_dwm folder under dwmsrc/config.
.TP
.B Super + Enter
Spawn terminal
.TP
.B Super + Q
Kill focused window
.TP
.B Super + 1..9
Switch tag
.TP
.B Super + Tilda (`)
Spawn scratchpad
.TP
.B Super + Space
Toggle floating on focused window
.TP
.B Super + Arrow Keys
Change focus between windows and desktops
.TP
.B Super + Left/Right Arrow Keys
Move focused window between desktops
.TP
.B Super + D
Spawn rofi launcher
.TP
.B Super + CTRL + Q
Spawn recompile script
.TP
.B Super + Shift + Q
Restart jeff_dwm
.TP
.B Super + CTRL + Shift + Q
Exit jeff_dwm
.TP
.B Super + P
Run rofi power menu script, where you can choose to either shut down, restart, suspend, hibernate, log out, or lock the screen.
.SH CUSTOMIZATION
jeff_dwm is customized by editing autorun.h, binds.h, config.h, script files, and misc configs.
To apply these changes, either recompile jeff_dwm to apply any .h file changes or run ./install.sh again
to apply all changes.
.SH SIGNALS
.TP
.B SIGHUP - 1
Restart the dwm process.
.TP
.B SIGTERM - 15
Cleanly terminate the dwm process.
.SH IPC 
jeff_dwm has an ipc system through dwm's ipc patch, with some minor tweaks. If you want to know more,
either check out dwm ipc's git page 
.B (https://github.com/mihirlad55/dwm-ipc)
or run
.B dwm-msg help
.SH ISSUES
Some windows do not like to render properly while floating. Either unfloating the window or
resizing the window should cause it to render properly. Other issues may stem from file names
or paths being incorrect. Be careful with config files and script names and extensions. 
.SH BUGS
Report all bugs to https://github.com/JeffofBread/jeff_dwm/issues.
